### PR TITLE
Using SafeMathLib

### PR DESCRIPTION
**Pull request by Janther**
Changes in contracts to use SafeMathLib instead of SafeMath

### CODE REVIEW

**Comment by Janther** [comment]
Solves #8

**Review by IsaacPayne — COMMENTED** [review]
Need to also add SafeMath to `ExchangeContract`

**Review by IsaacPayne — CHANGES_REQUESTED** [review]
SafeMath is missing from `ExchangeContract`

**Review by matt-lough — APPROVED** [review]

**Review by IsaacPayne — APPROVED** [review]

**Comment by IsaacPayne** [comment]
`ExchangeContract` changes being handled here: https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/pull/17

**Pull request merged**
